package br.com.gold.sintatico;

public enum TipoNo {
	NO_LISTDEF, NO_DEF, NO_LISTPARAM, NO_LISTPARAM2, NO_PARAM,
	NO_TIPO, NO_LISTCOMAN, NO_COMAN, NO_DECL, NO_ATRIB, NO_SE, 
	NO_LACO, NO_RET, NO_ENTRADA, NO_SAIDA, NO_CHAMADA, NO_LISTID,
	NO_LISTID2, NO_EXPARIT, NO_TERMO, NO_EXPARIT2, NO_TERMO2,
	NO_FATOR, NO_OP1, NO_OP2, NO_OPERANDO,NO_SENAO, NO_EXPREL,
	NO_OP3, NO_LISTARG, NO_LISTARG2, NO_TOKEN
}
